app = ""   # Fly.io will fill this when you create the app

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256